
		var tilemap = [ 
			{"tile" : "ocean", "pos" : [0, 0]}, 
			{"tile" : "ocean", "pos" : [1, 0]},
			{"tile" : "ocean", "pos" : [2, 0]},
			{"tile" : "ocean", "pos" : [3, 0]},
			{"tile" : "ocean", "pos" : [4, 0]},
			{"tile" : "ocean", "pos" : [5, 0]},
			{"tile" : "briny", "pos" : [6, 0]},
			{"tile" : "briny", "pos" : [7, 0]},
			{"tile" : "briny", "pos" : [8, 0]},
			{"tile" : "briny", "pos" : [9, 0]},
			{"tile" : "briny", "pos" : [10, 0]},
			{"tile" : "briny", "pos" : [11, 0]},

			{"tile" : "depths", "pos" : [-3, 1]}, 
			{"tile" : "depths", "pos" : [-2, 1]}, 
			{"tile" : "ocean", "pos" : [-1, 1]}, 
			{"tile" : "ocean", "pos" : [0, 1]}, 
			{"tile" : "ocean", "pos" : [1, 1]},
			{"tile" : "briny", "pos" : [2, 1]},
			{"tile" : "briny", "pos" : [3, 1]},
			{"tile" : "sand", "pos" : [4, 1]},
			{"tile" : "sand", "pos" : [5, 1]},
			{"tile" : "sand", "pos" : [6, 1]},
			{"tile" : "sand", "pos" : [7, 1]},
			{"tile" : "sand", "pos" : [8, 1]},
			{"tile" : "sand", "pos" : [9, 1]},

			{"tile" : "depths", "pos" : [-3, 2]}, 
			{"tile" : "depths", "pos" : [-2, 2]}, 
			{"tile" : "ocean", "pos" : [-1, 2]}, 
			{"tile" : "ocean", "pos" : [0, 2]}, 
			{"tile" : "ocean", "pos" : [1, 2]},
			{"tile" : "briny", "pos" : [2, 2]},
			{"tile" : "sand", "pos" : [3, 2]},
			{"tile" : "sand", "pos" : [4, 2]},
			{"tile" : "clay", "pos" : [5, 2]},
			{"tile" : "clay", "pos" : [6, 2]},

			{"tile" : "depths", "pos" : [-4, 3]}, 
			{"tile" : "depths", "pos" : [-3, 3]}, 
			{"tile" : "ocean", "pos" : [-2, 3]}, 
			{"tile" : "ocean", "pos" : [-1, 3]}, 
			{"tile" : "ocean", "pos" : [0, 3]}, 
			{"tile" : "ocean", "pos" : [1, 3]},
			{"tile" : "briny", "pos" : [2, 3]},
			{"tile" : "sand", "pos" : [3, 3]},
			{"tile" : "sand", "pos" : [4, 3]},

			{"tile" : "depths", "pos" : [-4, 4]},
			{"tile" : "depths", "pos" : [-3, 4]},
			{"tile" : "ocean", "pos" : [-2, 4]},
			{"tile" : "ocean", "pos" : [-1, 4]},
			{"tile" : "ocean", "pos" : [0, 4]}, 
			{"tile" : "ocean", "pos" : [1, 4]}, 
			{"tile" : "briny", "pos" : [2, 4]}, 
			{"tile" : "briny", "pos" : [3, 4]},
			{"tile" : "sand", "pos" : [4, 4]},

			{"tile" : "depths", "pos" : [-4, 5]}, 
			{"tile" : "depths", "pos" : [-3, 5]}, 
			{"tile" : "ocean", "pos" : [-2, 5]}, 
			{"tile" : "ocean", "pos" : [-1, 5]}, 
			{"tile" : "briny", "pos" : [0, 5]}, 
			{"tile" : "briny", "pos" : [1, 5]}, 
			{"tile" : "sand", "pos" : [2, 5]},
			{"tile" : "sand", "pos" : [3, 5]},

			{"tile" : "depths", "pos" : [-3, 6]}, 
			{"tile" : "ocean", "pos" : [-2, 6]}, 
			{"tile" : "ocean", "pos" : [-1, 6]}, 
			{"tile" : "briny", "pos" : [0, 6]}, 
			{"tile" : "briny", "pos" : [1, 6]}, 
			{"tile" : "sand", "pos" : [2, 6]}, 
			{"tile" : "loam", "pos" : [3, 6]},

			{"tile" : "ocean", "pos" : [-3, 7]}, 
			{"tile" : "ocean", "pos" : [-2, 7]}, 
			{"tile" : "ocean", "pos" : [-1, 7]}, 
			{"tile" : "briny", "pos" : [0, 7]}, 
			{"tile" : "briny", "pos" : [1, 7]}, 
			{"tile" : "river", "pos" : [2, 7]}, 
			{"tile" : "river", "pos" : [3, 7]},

			{"tile" : "ocean", "pos" : [-3, 8]}, 
			{"tile" : "ocean", "pos" : [-2, 8]}, 
			{"tile" : "ocean", "pos" : [-1, 8]}, 
			{"tile" : "briny", "pos" : [0, 8]}, 
			{"tile" : "briny", "pos" : [1, 8]},
			{"tile" : "loam", "pos" : [2, 8]}, 

			{"tile" : "ocean", "pos" : [-3, 9]}, 
			{"tile" : "briny", "pos" : [-2, 9]}, 
			{"tile" : "briny", "pos" : [-1, 9]}, 
			{"tile" : "sand", "pos" : [0, 9]}, 
			{"tile" : "sand", "pos" : [1, 9]},

			{"tile" : "ocean", "pos" : [-3, 10]}, 
			{"tile" : "briny", "pos" : [-2, 10]}, 
			{"tile" : "briny", "pos" : [-1, 10]}, 
			{"tile" : "sand", "pos" : [0, 10]},

			{"tile" : "grass", "pos" : [0, 11]},

			{"tile" : "forest", "pos" : [0, 12]},
			
			{"tile" : "forest", "pos" : [0, 13]},
			
			{"tile" : "forest", "pos" : [0, 14]}
		];